# fly.toml app configuration file generated for renio-go on 2024-10-31T22:27:36-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'renio-go'
primary_region = 'bog'

[build]

[env]
  APP_ENV = 'production'
  PORT = '8080'
  SEED = 'off'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
