migrate_dir=file://./db/migrations
database_url=REPLACE_ME
test_database_url=REPLACE_ME

migrate_up:
	goose -dir $(migrate_dir) postgres $(database_url) up 

migrate_reset:
	goose -dir $(migrate_dir) postgres '$(database_url)' reset

migrate_test_up:
	goose -dir $(migrate_dir) postgres '$(test_database_url)' up

migrate_test_reset:
	goose -dir $(migrate_dir) postgres '$(test_database_url)' reset

test: migrate_test_reset migrate_test_up
	APP_ENV=test go test -v -cover -count=1 ./...

dev:
	go run ./cmd/server/main.go
