migrate_dir=./db/migrations
database_url=REPLACE_ME
test_database_url=REPLACE_ME

migrate_up:
	goose -dir $(migrate_dir) postgres $(database_url) up

migrate_reset:
	goose -dir $(migrate_dir) postgres '$(database_url)' reset

migrate_test_up:
	goose -dir $(migrate_dir) postgres '$(test_database_url)' up

migrate_test_reset:
	goose -dir $(migrate_dir) postgres '$(test_database_url)' reset

test: migrate_test_reset migrate_test_up
	APP_ENV=test go test -v -cover -count=1 ./...

server:
	go run ./cmd/server/main.go

watch-server:
	air

postcss:
	bunx postcss-cli web/static/css/app.css -o web/static/css/build/bundle.css --watch & disown

rollup:
	bunx rollup --config

dev: postcss rollup watch-server
